# Trading Bot Configuration
# 
# Exchange configuration
exchange:
  name: mexc                # Supported: mexc, hyperliquid, binance, etc.

# Trading parameters
trading:
  pair: BTC/USDC                # Trading pair
  quote_amount: 50.0            # Amount in USDC per buy order
  price_offset: 700.0           # Price difference for limit orders (USDC)
  profit_threshold: 2.0         # Base profit threshold (2.0% = 1.02)
  rsi_period: 1                 # Days of data (1h candles) for RSI calculation
  rsi_oversold_threshold: 45.0  # RSI threshold for oversold condition (< 30 = buy signal)
  volatility_period: 7          # Days of data (4h candles) for volatility calculation
  volatility_adjustment: 50.0   # Profit threshold adjustment percentage per 1% volatility (50.0 = 50% adjustment per 1% volatility)
  
# Timing intervals
intervals:
  buy_interval_hours: 9     # Hours between buy attempts
  check_interval_minutes: 5 # Minutes between price/order checks

# Database configuration
database:
  path: db/bot.db           # SQLite database file path

# Logging configuration
logging:
  level: info               # Levels: debug, info, warn, error
  file: ""                  # Optional log file (empty = stdout only)

  # Web server configuration
web:
  port: ":8081"                 # Port for the web interface

# Note: Set API_KEY and API_SECRET environment variables for exchange access
