services:
  bot:
    image: zedalaye/simple-bot:latest
    container_name: bot-${EXCHANGE:-mexc}
    command: /app/bot
    volumes:
      - ./storage/${EXCHANGE:-mexc}/config.yml:/app/config.yml
      - ./storage/${EXCHANGE:-mexc}/db/:/app/db/
    env_file:
      - ./storage/${EXCHANGE:-mexc}/.env
      - ./storage/.env.tg
    restart: unless-stopped
    networks:
      - bot-network

  webui:
    image: zedalaye/simple-bot:latest
    container_name: webui-${EXCHANGE:-mexc}
    command: /app/web
    volumes:
      - ./storage/${EXCHANGE:-mexc}/config.yml:/app/config.yml
      - ./storage/${EXCHANGE:-mexc}/db/:/app/db/
    env_file:
      - ./storage/${EXCHANGE:-mexc}/.env
    ports:
      - "${WEB_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    name: ${EXCHANGE:-mexc}-network
    driver: bridge
