services:
  bot:
    image: zedalaye/simple-bot:latest
    container_name: bot-${EXCHANGE}
    command: /app/bot
    volumes:
      - ./storage/${EXCHANGE}/config.yml:/app/config.yml
      - ./storage/${EXCHANGE}/db/:/app/db/
    env_file:
      - ./storage/${EXCHANGE}/.env
      - ./storage/.env.tg
    environment:
      - BOT_RELOAD_TOKEN=${RELOAD_TOKEN}
    restart: unless-stopped
    networks:
      - bot-network

  webui:
    image: zedalaye/simple-bot:latest
    container_name: webui-${EXCHANGE}
    command: /app/web
    volumes:
      - ./storage/${EXCHANGE}/config.yml:/app/config.yml
      - ./storage/${EXCHANGE}/db/:/app/db/
    env_file:
      - ./storage/${EXCHANGE}/.env
    environment:
      - BOT_RELOAD_TOKEN=${RELOAD_TOKEN}
    ports:
      - "${WEB_PORT:-8080:8080}"
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    name: ${EXCHANGE}-network
    driver: bridge
