# Trading Bot Configuration
# 
# Exchange configuration
exchange:
  name: hyperliquid             # Supported: mexc, hyperliquid, binance, etc.
  
# Trading parameters (strategy-specific parameters are configured per strategy)
trading:
  pair: UBTC/USDC               # Default trading pair for this exchange
  
# Timing intervals
intervals:
  check_interval_minutes: 5     # Minutes between price/order checks

# Database configuration
database:
  path: db/bot.db               # SQLite database file path

# Logging configuration
logging:
  level: info                   # Levels: debug, info, warn, error
  file: ""                      # Optional log file (empty = stdout only)

# Web server configuration
web:
  port: ":8080"                 # Port for the web interface
  docker: "8082:8080"           # Port mapping for Docker

# Note: Set API_KEY and API_SECRET environment variables for exchange access
